name: firebase-deploy
on: 
  push:
    paths:
      - site/**
      
env:
  PROJECT_PATH: site/

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to GitHub
        uses: actions/checkout@v3
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
