name: header
on: [push]
jobs:
  add-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: make-header
        run:
          python ./scripts/header.py
